"""First Migration

Revision ID: c61336376948
Revises: 
Create Date: 2021-11-30 06:06:54.661345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61336376948'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorten_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('short_web', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shorten_urls')
    # ### end Alembic commands ###
